# Numpy

Python List : Heterogeneous , scattered , type checking on every element , 10-100x slower.

Numpy array : Homogeneous,type checking once.

Numpy is a package that aims to efficiently process and store high-dimensional data. It intends to bring performance and functionality improvements for numerical computing.

1. nd_array can be operated in vectorized form by taking benefit from SIMD stream.
2. No overhead of typechecking.
3. Easy to load and save files.
4. Other packages can efficiently interact with Numpy.
5. Provides inbuilt implementation for alegbra,statistics,broadcasting,etc.


Pros => Native speed , Homogenity, Contigious memory.

Vectorization means performing operations on the whole array at once instead of using loops.

Concept of 1D , 2D , 3D , 4d and many more multidimensional. 

(2,3,3,4)

(2) 3D arrays -> 
(3) 2D arrays -> 
(3) 1D arrays -> 
1D array --- 4 elements each

In [1]:
import numpy as np

arr = np.zeros([1, 2, 3, 4, 5])
print(arr)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]]


In [2]:
%%time

N = 100000000

l1 = list(range(N)) #  it will create a list from 0 to N-1

for i in range(N):
    l1[i] = l1[i] * l1[i] # it will square each element in the list

CPU times: total: 10.2 s
Wall time: 35 s


In [3]:
%%time

N = 100000000

l2 = list(range(N)) #  it will create a list from 0 to N-1

l2 = [i * i for i in l2] # it will square each element in the list using list comprehension i.e inline code

CPU times: total: 7.42 s
Wall time: 54.1 s


In [4]:
%%time

N = 100000000

l3 = list(range(N)) #  it will create a list from 0 to N-1

# map(function, iterable) --> it will apply the function to each element in the iterable and return a map object which is an iterator

l3 = map(lambda x: x * x, l3) # it will square each element in the list using map function and lambda function i.e anonymous function

CPU times: total: 1.59 s
Wall time: 15.7 s


In [8]:
import numpy as np

In [11]:
%%time

#create a numpy array from 0 to N-1 and square each element in the numpy array

N = 100000000

arr = np.arange(N) # it will create a numpy array from 0 to N-1

arr = arr * arr # it will square each element in the numpy array

CPU times: total: 641 ms
Wall time: 1.5 s
