# Numpy

Python List : Heterogeneous , scattered , type checking on every element , 10-100x slower.

Numpy array : Homogeneous,type checking once.

Numpy is a package that aims to efficiently process and store high-dimensional data. It intends to bring performance and functionality improvements for numerical computing.

1. nd_array can be operated in vectorized form by taking benefit from SIMD stream.
2. No overhead of typechecking.
3. Easy to load and save files.
4. Other packages can efficiently interact with Numpy.
5. Provides inbuilt implementation for alegbra,statistics,broadcasting,etc.


Pros => Native speed , Homogenity, Contigious memory.

Vectorization means performing operations on the whole array at once instead of using loops.

Concept of 1D , 2D , 3D , 4d and many more multidimensional. 

(2,3,3,4)

(2) 3D arrays -> 
(3) 2D arrays -> 
(3) 1D arrays -> 
1D array --- 4 elements each

In [1]:
import numpy as np

arr = np.zeros([1, 2, 3, 4, 5])
print(arr)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]]


In [2]:
%%time

N = 100000000

l1 = list(range(N)) #  it will create a list from 0 to N-1

for i in range(N):
    l1[i] = l1[i] * l1[i] # it will square each element in the list

CPU times: total: 10.2 s
Wall time: 35 s


In [3]:
%%time

N = 100000000

l2 = list(range(N)) #  it will create a list from 0 to N-1

l2 = [i * i for i in l2] # it will square each element in the list using list comprehension i.e inline code

CPU times: total: 7.42 s
Wall time: 54.1 s


In [4]:
%%time

N = 100000000

l3 = list(range(N)) #  it will create a list from 0 to N-1

# map(function, iterable) --> it will apply the function to each element in the iterable and return a map object which is an iterator

l3 = map(lambda x: x * x, l3) # it will square each element in the list using map function and lambda function i.e anonymous function

CPU times: total: 1.59 s
Wall time: 15.7 s


In [8]:
import numpy as np

In [11]:
%%time

#create a numpy array from 0 to N-1 and square each element in the numpy array

N = 100000000

arr = np.arange(N) # it will create a numpy array from 0 to N-1

arr = arr * arr # it will square each element in the numpy array

CPU times: total: 641 ms
Wall time: 1.5 s


# How to create numpy arrays?

In [1]:
# 1. Using a Python List (Best for manual data)

import numpy as np

arr1 = np.array([7, 77, 10, 9, 8])

In [ ]:
print(type(arr1)) # it will print the type of arr1 which is numpy.ndarray

print(arr1.shape) # it will print the shape of arr1 which is (5,)

print(arr1.ndim) # it will print the number of dimensions of arr1 which is 1D

print(arr1.itemsize) # it will print the size of each element in arr1 which is 8 bytes i.e 64 bits



<class 'numpy.ndarray'>
(5,)
1
8


In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(type(arr2)) # it will print the type of arr2 which is numpy.ndarray

print(arr2.shape) # it will print the shape of arr2 which is (2, 3) which means 2 rows and 3 columns

print(arr2.ndim) # it will print the number of dimensions of arr2 which is 2D

print(arr2.itemsize) # it will print the size of each element in arr2 which is 8 bytes and the total size of arr2 which is 48 bytes because there are 6 elements in arr2 and each element is 8 bytes


<class 'numpy.ndarray'>
(2, 3)
2
8


In [7]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(type(arr3)) # it will print the type of arr3 which is numpy.ndarray

print(arr3.shape) # it will print the shape of arr3 which is (2, 2, 3) which means 2 blocks, 2 rows and 3 columns

print(arr3.ndim) # it will print the number of dimensions of arr3 which is 3D   

print(arr3.itemsize) # it will print the size of each element in arr3 which is 8 bytes and the total size of arr3 which is 96 bytes because there are 12 elements in arr3 and each element is 8 bytes

<class 'numpy.ndarray'>
(2, 2, 3)
3
8


In [8]:
# 2. Using arange() function (Best for large data) in combination with reshape() function to create multi-dimensional arrays-----Best for sequence generation

#1D array

ar1 = np.arange(5) # it will create a 1D array from 0 to 4

print(type(ar1)) # it will print the type of ar1 which is numpy.ndarray

print(ar1.shape) # it will print the shape of ar1 which is (5,)

print(ar1.ndim) # it will print the number of dimensions of ar1 which is 1

print(ar1.itemsize) # it will print the size of each element in ar1 which is 8 bytes and the total size of ar1 which is 40 bytes because there are 5 elements in ar1 and each element is 8 bytes



<class 'numpy.ndarray'>
(5,)
1
8


In [11]:
# 2D array

# ar2 = np.arange(12).reshape(2, 8)  --- it will create a 2D array from 0 to 11 and reshape it to 2 rows and 8 columns but it will give an error because there are only 12 elements in ar2 and we are trying to reshape it to 16 elements

ar2 = np.arange(12).reshape(2, 6) # it will create a 2D array from 0 to 11 and reshape it to 2 rows and 6 columns

print(type(ar2)) # it will print the type of ar2 which is numpy.ndarray

print(ar2.shape) # it will print the shape of ar2 which is (2, 6)

print(ar2.ndim) # it will print the number of dimensions of ar2 which is 2

print(ar2.itemsize) # it will print the size of each element in ar2 which is 8 bytes and the total size of ar2 which is 96 bytes because there are 12 elements in ar2 and each element is 8 bytes

<class 'numpy.ndarray'>
(2, 6)
2
8


In [13]:
# 3D array

ar3 = np.arange(18).reshape(2, 3, 3) # it will create a 3D array from 0 to 17 and reshape it to 2 blocks, 3 rows and 3 columns i.e 2 * 3 * 3 = 18 elements

print(ar3) # it will print the 3D array ar3

print(type(ar3)) # it will print the type of ar3 which is numpy.ndarray

print(ar3.shape) # it will print the shape of ar3 which is (2, 3, 3)

print(ar3.ndim) # it will print the number of dimensions of ar3 which is 3

print(ar3.itemsize) # it will print the size of each element in ar3 which is 8 bytes and the total size of ar3 which is 144 bytes because there are 18 elements in ar3 and each element is 8 bytes


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
<class 'numpy.ndarray'>
(2, 3, 3)
3
8


3. Using Zeroes 

In [14]:
arz = np.zeros((2,3,3)) # it will create a 3D array of zeros with 2 blocks, 3 rows and 3 columns

print(arz) # it will print the 3D array arz

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [15]:
# 4. using ones() function to create an array of ones

np.ones((2,3,3)) # it will create a 3D array of ones with 2 blocks, 3 rows and 3 columns

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
np.ones(2) # it will create a 1D array of ones with 2 elements

array([1., 1.])

In [16]:
# 5. function full() to create an array of any value

np.full((2,3,3), 11) # it will create a 3D array of 11s with 2 blocks, 3 rows and 3 columns

array([[[11, 11, 11],
        [11, 11, 11],
        [11, 11, 11]],

       [[11, 11, 11],
        [11, 11, 11],
        [11, 11, 11]]])

In [ ]:
# Random arrays: Used in Ml , statistics, data analysis, etc.


# numpy.random module

In [ ]:
# 1. rand() -> Random float values : it will create an array of random float values between 0 and 1

r1 = np.random.rand(5) # it will create a 1D array of random float values between 0 and 1 with 5 elements

print(r1) # it will print the 1D array r1 of random float values between 0 and 1 with 5 elements

r11 = np.random.rand(2,2,3) # it will create a 3D array of random float values between 0 and 1 with 2 blocks, 2 rows and 3 columns

print(r11) # it will print the 3D array r11 of random float values between 0 and 1 with 2 blocks, 2 rows and 3 columns i.e 2 * 2 * 3 = 12 elements

[0.68687224 0.24006435 0.72982045 0.12697561 0.7586549 ]
[[[0.51485574 0.8593916  0.85948132]
  [0.02264801 0.7956819  0.45090072]]

 [[0.83393216 0.17796634 0.36331525]
  [0.2414209  0.18789285 0.04631741]]]


In [21]:
# 2. randint() -> Random integer values : it will create an array of random integer values between a specified range

r3 = np.random.randint(1, 10, 5) # it will create a 1D array of random integer values between 1 and 9 with 5 elements  ---(low, high, size)

print(r3) # it will print the 1D array r3 of random integer values between 1 and 9 with 5 elements

r5 = np.random.randint(1, 100, (2,3,5)) # it will create a 3D array of random integer values between 1 and 99 with 2 blocks, 3 rows and 5 columns i.e 2 * 3 * 5 = 30 elements

print(r5) # it will print the 3D array r5 of random integer values between 1 and 99 with 2 blocks, 3 rows and 5 columns i.e 2 * 3 * 5 = 30 elements

[3 9 9 4 5]
[[[39 62 38 74 58]
  [ 6 24  7 41 33]
  [52 20 64 92 24]]

 [[91 74 26 91 10]
  [67 28 97 75 12]
  [26 91 77 64 32]]]


In [22]:
# 3. randn() -> Random float values from a normal distribution : it will create an array of random float values from a normal distribution with mean 0 and standard deviation 1

# normal distribution is a continuous probability distribution that is symmetric around the mean, showing that data near the mean are more frequent in occurrence than data far from the mean. It is also known as Gaussian distribution. The randn() function in numpy is used to generate random float values from a normal distribution with mean 0 and standard deviation 1.

r6 = np.random.randn(3,3) # it will create a 2D array of random float values from a normal distribution with mean 0 and standard deviation 1 with 3 rows and 3 columns

print(r6) # it will print the 2D array r6 of random float values from a normal distribution with mean 0 and standard deviation 1 with 3 rows and 3 columns

[[-0.62957658  0.27947512 -0.96440194]
 [-0.42919358 -0.92983258  0.26956869]
 [ 0.64254621 -0.72935171 -0.93620239]]


In [23]:
# Uniform () -> it will create an array of random float values between a specified range

arru = np.random.uniform(1, 10, (2,3)) # it will create a 2D array of random float values between 1 and 10 with 2 rows and 3 columns i.e 2 * 3 = 6 elements

print(arru) # it will print the 2D array arru of random float values between 1 and 10 with 2 rows and 3 columns i.e 2 * 3 = 6 elements

[[4.07655537 2.14646487 4.84852708]
 [3.04473977 7.4694039  6.44069847]]


In [24]:
# random Boolean arrays

arrb = np.random.choice([True, False], size=(2,3)) # it will create a 2D array of random Boolean values with 2 rows and 3 columns i.e 2 * 3 = 6 elements

print(arrb) # it will print the 2D array arrb of random Boolean values with 2 rows and 3 columns i.e 2 * 3 = 6 elements

[[False  True  True]
 [ True  True False]]


# Case Study : Monte Carlo Estimation

Using Numpy to estimate the area of a circle quadrant within a 1*1 square demonstrates the power of combining random number generation with vectorized operations.

STEP 1 : Generate Points
        Create a 2D array of (x,y) coordinates using np.random.rand()

STEP 2 : Compute Distance
        Calculate x^2 + y^2 for all points simultaneously in a vectorized form.

STEP 3 : Filter Hits and Estimate
        Identify points where distance <= 1. The ratio of hits to total points is the area.

Monte Carlo Estimation is a statistical technique that uses random sampling
to estimate mathematical values such as area, probability, or the value of π (pi).Instead of solving mathematically, we use many random points and approximate the result.

In [1]:
import numpy as np

# Number of random points
N = 100000000

# Generate random points
points = np.random.rand(N, 2)  # it will create a 2D array of random float values between 0 and 1 with N rows and 2 columns i.e N points with x and y coordinates

# Extract coordinates
x = points[:, 0]   # it will extract the first column of points which is the x coordinates and store it in x

y = points[:, 1]   # it will extract the second column of points which is the y coordinates and store it in y

# Compute x² + y²
distance = x**2 + y**2    

# Check points inside quarter circle
hits = distance <= 1   # it will check if the distance of each point from the origin is less than or equal to 1 and return a Boolean array hits where True means the point is inside the quarter circle and False means the point is outside the quarter circle

# Count hits
inside_count = np.sum(hits) # it will count the number of True values in hits which is the number of points inside the quarter circle and store it in inside_count

# Estimate area
estimated_area = inside_count / N  # it will estimate the area of the quarter circle by dividing the number of points inside the quarter circle by the total number of points N and store it in estimated_area

print("Estimated Area =", estimated_area)

print("Actual Area =", np.pi/4)   # it will print the actual area of the quarter circle which is π/4 because the area of a circle is πr² and the radius of the quarter circle is 1 so the area of the quarter circle is π * 1² / 4 = π/4

Estimated Area = 0.78536533
Actual Area = 0.7853981633974483


In [3]:
import numpy as np
N = 10000000

points = np.random.rand(N,2)

x = points[:,0]
y = points[:,1]

hits = (x**2 + y**2 <= 1)

pi_estimate = 4 * np.sum(hits) / N

print(pi_estimate)

3.1417508


# Indexing and Slicing

In [4]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [5]:
# print 6 

print(arr[1,2]) # it will print the element at the second row and third column of arr which is 6

#print 8

print(arr[2,1]) # it will print the element at the third row and second column of arr which is 8

# print middle row

print(arr[1]) # it will print the second row of arr which is [4, 5, 6]

# print diagonal elements

print(arr.diagonal()) # it will print the diagonal elements of arr which are [1, 5, 9]

# print last two rows

print(arr[1:3]) # it will print the last two rows of arr which are [[4, 5, 6], [7, 8, 9]]

# print last column

print(arr[:,2]) # it will print the last column of arr which is [3, 6, 9]
print(arr[:,-1]) # it will print the last column of arr which is [3, 6, 9]

# print middle column
print(arr[:,1]) # it will print the middle column of arr which is [2, 5, 8]

#print last two columns
print(arr[:,1:3]) # it will print the last two columns of arr which are [[2, 3], [5, 6], [8, 9]]

#print first two columns
print(arr[:,0:2]) # it will print the first two columns of arr which are [[1, 2], [4, 5], [7, 8]]

print(arr[:,:]) # it will print the entire array arr which is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# : as a first index means all rows and : as a second index means all columns so arr[:,:] means all rows and all columns which is the entire array arr

print(arr[1:3, 1:3]) # it will print the last two rows and last two columns of arr which are [[5, 6], [8, 9]]




6
8
[4 5 6]
[1 5 9]
[[4 5 6]
 [7 8 9]]
[3 6 9]
[3 6 9]
[2 5 8]
[[2 3]
 [5 6]
 [8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


3D Indexing and Slicing

In [ ]:
arr3D = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7,8, 9]],
                  
                  [[10, 11, 12], 
                   [13, 14, 15],
                   [16, 17, 18]]])

In [7]:
print(arr3D[1,1,2]) # it will print the element at the second block, second row and third column of arr3D which is 15

15


In [8]:
print(arr3D[0,:,2]) # it will print the third column of the first block of arr3D which is [3, 6, 9]
print(arr3D[1,:,2]) # it will print the third column of the second block of arr3D which is [12, 15, 18]

[3 6 9]
[12 15 18]


In [9]:
print(arr3D[0,:,2]) # 0 means first 2D , : means all rows , 2 means third column of the first block of arr3D which is [3, 6, 9]

[3 6 9]


In [10]:
print(arr3D[0,1,:]) # it will print the second row of the first block of arr3D which is [4, 5, 6]

[4 5 6]


In [11]:
print(arr3D[:,1,:]) # : means both 2D , 1 means  second row , : means all columns so it will print the second row of both blocks of arr3D which is [[4, 5, 6], [13, 14, 15]]

[[ 4  5  6]
 [13 14 15]]


In [12]:
# print last row of last block

print(arr3D[1,2,:]) # it will print the last row of the second block of arr3D which is [16, 17, 18]

[16 17 18]


In [13]:
# print second column of first block

print(arr3D[0,:,1]) # it will print the second column of the first block of arr3D which is [2, 5, 8]

[2 5 8]


# Numpy Broadcasting  

Perform operations on two differently shaped matrices.

use the Right-left rule.

1. Dimensions is equal.
2. One dimension in 1.

i.e (4,)   ---->    (1,4)   ----- Now compatible with (2,3)